# Generated by Django 6.0.3 on 2026-04-13 03:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('diet_type', models.CharField(choices=[('high_protein', 'High Protein'), ('keto', 'Keto'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('omnivore', 'Omnivore'), ('other', 'Other')], default='omnivore', max_length=32)),
                ('per_100g_kcal', models.DecimalField(decimal_places=2, help_text='Calories per 100g', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_100g_protein', models.DecimalField(decimal_places=2, help_text='Protein grams per 100g', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_100g_carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrate grams per 100g', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_100g_fat', models.DecimalField(decimal_places=2, help_text='Fat grams per 100g', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('source', models.CharField(blank=True, help_text='Dataset/source name such as USDA/FSA', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('per_100g_kcal__gte', 0)), name='fooditem_kcal_non_negative'), models.CheckConstraint(condition=models.Q(('per_100g_protein__gte', 0)), name='fooditem_protein_non_negative'), models.CheckConstraint(condition=models.Q(('per_100g_carbs__gte', 0)), name='fooditem_carbs_non_negative'), models.CheckConstraint(condition=models.Q(('per_100g_fat__gte', 0)), name='fooditem_fat_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_date', models.DateField(db_index=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=16)),
                ('intake_weight_grams', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('actual_kcal', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_protein', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_carbs', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_fat', models.DecimalField(decimal_places=2, editable=False, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_logs', to='nutrition.fooditem')),
            ],
            options={
                'ordering': ('-intake_date', '-created_at'),
                'indexes': [models.Index(fields=['intake_date', 'meal_type'], name='nutrition_m_intake__5ebcb9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('intake_weight_grams__gt', 0)), name='meallog_weight_positive'), models.CheckConstraint(condition=models.Q(('actual_kcal__gte', 0)), name='meallog_kcal_non_negative'), models.CheckConstraint(condition=models.Q(('actual_protein__gte', 0)), name='meallog_protein_non_negative'), models.CheckConstraint(condition=models.Q(('actual_carbs__gte', 0)), name='meallog_carbs_non_negative'), models.CheckConstraint(condition=models.Q(('actual_fat__gte', 0)), name='meallog_fat_non_negative')],
            },
        ),
    ]
