# Generated by Django 6.0.3 on 2026-04-13 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meallog',
            name='nutrition_m_intake__5ebcb9_idx',
        ),
        migrations.AddField(
            model_name='meallog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'intake_date'], name='nutrition_m_user_id_caf474_idx'),
        ),
        migrations.AddIndex(
            model_name='meallog',
            index=models.Index(fields=['user', 'intake_date', 'meal_type'], name='nutrition_m_user_id_d8fc30_idx'),
        ),
    ]
