# Generated by Django 6.0.3 on 2026-04-17 03:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_backfill_meallog_user_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
        ),
        migrations.CreateModel(
            name='UserNutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kcal', models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_protein', models.DecimalField(decimal_places=2, default=Decimal('120'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_carbs', models.DecimalField(decimal_places=2, default=Decimal('220'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('target_fat', models.DecimalField(decimal_places=2, default=Decimal('67'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meallog',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_logs', to='nutrition.fooditem'),
        ),
        migrations.CreateModel(
            name='CustomFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('per_100g_kcal', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_100g_protein', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_100g_carbs', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('per_100g_fat', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='meallog',
            name='custom_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meal_logs', to='nutrition.customfooditem'),
        ),
        migrations.AddConstraint(
            model_name='meallog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('food_item__isnull', False), ('custom_food__isnull', True)), models.Q(('food_item__isnull', True), ('custom_food__isnull', False)), _connector='OR'), name='meallog_exactly_one_food_source'),
        ),
        migrations.AddField(
            model_name='foodfavorite',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='foodfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='custom_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='nutrition.customfooditem'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.recipe'),
        ),
        migrations.AddField(
            model_name='usernutritiontarget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customfooditem',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='custom_food_unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='customfooditem',
            constraint=models.CheckConstraint(condition=models.Q(('per_100g_kcal__gte', 0)), name='custom_food_kcal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customfooditem',
            constraint=models.CheckConstraint(condition=models.Q(('per_100g_protein__gte', 0)), name='custom_food_protein_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customfooditem',
            constraint=models.CheckConstraint(condition=models.Q(('per_100g_carbs__gte', 0)), name='custom_food_carbs_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customfooditem',
            constraint=models.CheckConstraint(condition=models.Q(('per_100g_fat__gte', 0)), name='custom_food_fat_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='foodfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'food_item'), name='food_favorite_unique_per_user'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='recipe_unique_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('food_item__isnull', False), ('custom_food__isnull', True)), models.Q(('food_item__isnull', True), ('custom_food__isnull', False)), _connector='OR'), name='recipe_item_exactly_one_food_source'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__gt', 0)), name='recipe_item_weight_positive'),
        ),
    ]
