# Generated by Django 6.0.3 on 2026-04-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_foodfavorite_recipe_recipeitem_usernutritiontarget_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customfooditem',
            name='custom_food_unique_name_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='customfooditem',
            name='custom_food_kcal_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='customfooditem',
            name='custom_food_protein_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='customfooditem',
            name='custom_food_carbs_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='customfooditem',
            name='custom_food_fat_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_unique_name_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='recipe_item_exactly_one_food_source',
        ),
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='recipe_item_weight_positive',
        ),
        migrations.RemoveConstraint(
            model_name='meallog',
            name='meallog_exactly_one_food_source',
        ),
        migrations.RemoveField(
            model_name='customfooditem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='custom_food',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='recipeitem',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='custom_food',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeItem',
        ),
        migrations.DeleteModel(
            name='CustomFoodItem',
        ),
    ]
