from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from nutrition.views import (
    AdvancedAnalyticsAPIView,
    ChangePasswordAPIView,
    CurrentSessionsAPIView,
    CustomFoodItemDetailAPIView,
    CustomFoodItemListCreateAPIView,
    CurrentUserAPIView,
    CustomTokenObtainPairAPIView,
    DeleteAccountAPIView,
    DailySummaryAPIView,
    FoodFavoriteDeleteAPIView,
    FoodFavoriteListCreateAPIView,
    FoodItemListAPIView,
    FoodRecentAPIView,
    LogoutAPIView,
    MealLogBulkCreateAPIView,
    MealLogDetailAPIView,
    MealLogQuickCreateAPIView,
    MealLogListCreateAPIView,
    NutritionTrendsAPIView,
    PasswordResetConfirmAPIView,
    PasswordResetRequestAPIView,
    RecipeDetailAPIView,
    RecipeListCreateAPIView,
    RevokeAllSessionsAPIView,
    RegisterAPIView,
    UserDataExportAPIView,
    UserNutritionTargetAPIView,
)

urlpatterns = [
    path("auth/register/", RegisterAPIView.as_view(), name="auth-register"),
    path("auth/token/", CustomTokenObtainPairAPIView.as_view(), name="auth-token-obtain-pair"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="auth-token-refresh"),
    path("auth/me/", CurrentUserAPIView.as_view(), name="auth-me"),
    path("auth/logout/", LogoutAPIView.as_view(), name="auth-logout"),
    path("auth/password/change/", ChangePasswordAPIView.as_view(), name="auth-password-change"),
    path("auth/password/reset/request/", PasswordResetRequestAPIView.as_view(), name="auth-password-reset-request"),
    path("auth/password/reset/confirm/", PasswordResetConfirmAPIView.as_view(), name="auth-password-reset-confirm"),
    path("auth/account/", DeleteAccountAPIView.as_view(), name="auth-account-delete"),
    path("auth/export/", UserDataExportAPIView.as_view(), name="auth-export"),
    path("auth/sessions/", CurrentSessionsAPIView.as_view(), name="auth-sessions"),
    path("auth/sessions/revoke-all/", RevokeAllSessionsAPIView.as_view(), name="auth-sessions-revoke-all"),
    path("foods/", FoodItemListAPIView.as_view(), name="food-item-list"),
    path("foods/recent/", FoodRecentAPIView.as_view(), name="food-item-recent"),
    path("foods/favorites/", FoodFavoriteListCreateAPIView.as_view(), name="food-favorite-list-create"),
    path("foods/favorites/<int:food_item_id>/", FoodFavoriteDeleteAPIView.as_view(), name="food-favorite-delete"),
    path("custom-foods/", CustomFoodItemListCreateAPIView.as_view(), name="custom-food-list-create"),
    path("custom-foods/<int:pk>/", CustomFoodItemDetailAPIView.as_view(), name="custom-food-detail"),
    path("recipes/", RecipeListCreateAPIView.as_view(), name="recipe-list-create"),
    path("recipes/<int:pk>/", RecipeDetailAPIView.as_view(), name="recipe-detail"),
    path("logs/", MealLogListCreateAPIView.as_view(), name="meal-log-list-create"),
    path("logs/quick/", MealLogQuickCreateAPIView.as_view(), name="meal-log-quick-create"),
    path("logs/bulk/", MealLogBulkCreateAPIView.as_view(), name="meal-log-bulk-create"),
    path("logs/<int:pk>/", MealLogDetailAPIView.as_view(), name="meal-log-detail"),
    path("logs/daily-summary/", DailySummaryAPIView.as_view(), name="meal-log-daily-summary"),
    path("profile/targets/", UserNutritionTargetAPIView.as_view(), name="profile-targets"),
    path("analytics/trends/", NutritionTrendsAPIView.as_view(), name="nutrition-trends"),
    path("analytics/advanced/", AdvancedAnalyticsAPIView.as_view(), name="nutrition-advanced-analytics"),
]
